---
name: Sync Docs to Gists

on:
  push:
    branches:
      - main
    paths:
      - 'docs/INFO.md'
      - 'docs/SHOP.md'
      - 'docs/CHANGELOG.md'

jobs:
  sync-gists:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Sync INFO.md to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 07fc57925e624dfc31a08976bc7cc457
          file_path: docs/INFO.md
          file_name: INFO.md
      - name: Sync SHOP.md to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 1facc246a6b8d7a4e3b8aace74993e3d
          file_path: docs/SHOP.md
          file_name: SHOP.md
      - name: Sync CHANGELOG.md to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 288b8a2707aa41b01d440ee4f207a831
          file_path: docs/CHANGELOG.md
          file_name: CHANGELOG.md
